### ISSUE TITLE
Update tests and cloudbridge code to restrict resource names

### ISSUE THREAD

**Issue by mbookman** [gvlproject/cloudbridge#55]
In https://github.com/gvlproject/cloudbridge/pull/44#issuecomment-308033516, @nuwang indicated:

> ... I was thinking that perhaps we should consider enforcing RFC1035 for all names in cloudbridge and document it at an interface level. The only thing that bugs me a little is the lack of spaces for a descriptive name. Perhaps it can be "RFC1035+spaces allowed" and GCE can replace spaces with underscores where necessary?

From the GCP implementation perspective, this would be great. We don't really have any good alternatives (note that GCE accepts _dashes_, rather than _underscores_).

The current set of tests, run against GCP, are failing because resource names in the tests do not follow the above assumptions. Can we get the tests updated, along with any anticipated enforcement elsewhere by the CloudBridge API?

Thanks.

**Comment by nuwang** [comment]
@mbookman @baizhang @chiniforooshan This commit: https://github.com/gvlproject/cloudbridge/commit/cc5a86a2ba5870db9e09b251c3e3dd1a33fcc832 refactors the tests so that we can soon uniformly enforce identifier checks across the whole of cloudbridge. I was trying to write the enforcement code now and ran across a few issues. Enis, Marcus and I had a discussion about them, so I'll just write down our thoughts so far.

The main issue is that the instance name property must conform to the following:
https://cloud.google.com/compute/docs/reference/beta/instances#name

However, labels are slightly different:
https://cloud.google.com/compute/docs/labeling-resources#restrictions

In particular, labels allow for underscores, and international characters. However, the instance name does not appear to allow for international characters. So if we have an end-user specify a name in CloudLaunch using some international characters for example, we can use that to set the GCE label, but can't necessarily set the GCE instance name.

The solution we thought of therefore, was to autogenerate the GCE instance name. In CloudBridge, the ID is never displayed to the end-user, but the name is. Since the GCE implementation maps the cloudbridge ID to the GCE instance name, and the cloudbridge name to a GCE label, this will work ok.

The downside of this is that, if you view instances created through cloudbridge in the GCE console, they will have that autogenerated name. So using something like a UUID is probably undesirable, as that would make no sense to the user. To mitigate that, we can use the name that was used in cloudbridge at instance  launch time, and apply a fixed transformation to convert it into a valid GCE instance name. We then check whether an instance with that name already exists. If it does, we append a counter, and try again. If that exists too, we make the counter 2 and so on.

In the meantime, cloudbridge can enforce constraints that match GCE labels, which would be something like the following
"Cloudbridge identifiers must be 1-63 characters long, and comply with
    RFC1035. In addition, identifiers should contain only letters,
    numeric characters, spaces, underscores, and dashes. International
    characters are allowed."

Which is the same as GCE labels, except that spaces are allowed, as are uppercase/lowercase characters. Each provider implementation  can perform additional simple transformations (e.g. replace spaces with underscores, convert upper to lower), so that things just work across all providers.

What do you think?

**Comment by chiniforooshan** [comment]
> To mitigate that, we can use the name that was used in cloudbridge at instance launch time, and apply a fixed transformation to convert it into a valid GCE instance name. We then check whether an instance with that name already exists. If it does, we append a counter, and try again. If that exists too, we make the counter 2 and so on.

How does this work for `find` methods, for example?

**Comment by nuwang** [comment]
Noting the meeting outcome for completeness:

CloudBridge:
   * will implement the same restrictions as GCE labels across the whole library

CloudLaunch:
* Will not allow upper case letters and will make the restrictions visible to the user.
* Will label field as "host name" or some such to make the restrictions more expected for the user.

**Comment by nuwang** [comment]
Name enforcement is now done through these tests: https://github.com/gvlproject/cloudbridge/commit/980a6f6e460ce063c8d0169a488a857513817290

It needs to be enhanced a little, so that names are also enforced at object creation time, but as of now, all test object names conform to GCE label restrictions.

**Comment by nuwang** [comment]
This has been completed in: https://github.com/gvlproject/cloudbridge/pull/71

**Comment by nuwang** [comment]
@mbookman @chiniforooshan @baizhang 
I should have added. You can call the inherited resource method self.assert_valid_resource_name(name) at the top of each method to ensure that the name is validated before use. e.g. https://github.com/gvlproject/cloudbridge/pull/71/files#diff-bbda26f5170ea722a751387766bcf77aR575

If using it from a service, you'll have to call it through the resource class: https://github.com/gvlproject/cloudbridge/pull/71/files#diff-d74c202c32a8f1515ba25b70dbb8252fR214

Using the correct resource class is necessary since child classes may override behaviour (e.g. Buckets have different naming restrictions and BucketObjects can be any valid unix path)
