### ISSUE TITLE
v0.4 interface changes RFC

### ISSUE THREAD

**Issue by afgane** [gvlproject/cloudbridge#69]
After some discussions and based on using CloudBridge for developing CloudLaunch, we're thinking about a few changes to the interface with the intent of providing a more consistent experience and better logical grouping of services.

We've already made changes to the networking side of the library where multiple services got pushed under `provider.networking` vs. mixing `NetworkService` and`SubnetService` under `provider.network`: https://github.com/gvlproject/cloudbridge/commit/98eebf2546c58250959c56815475fb743908e070. In the process, we also added `RouterService`.

We are also in favor of the following changes:

- [x] Rename `provider.compute.instance_types` → `provider.compute.vm_types` and consequently `InstanceType` resource to `VMType`
- [x] Rename method `Instance.terminate`→ `Instance.delete`
- [x] Rename `provider.security.security_groups` → `provider.security.vm_firewall`
- [ ] Plan for eventual implementation of `provider.security.net_firewall`, representing network ACLs
- [x] Join `provider.block_store` and `provider.object_store` into `provider.storage`. In addition, rename notion of `object_store` into `buckets` so `provider.storage` would have the following three modules: `volumes`, `snapshots`, and `buckets`
- [x] Make firewall rules standalone (The resultant firewall rules class may potentially be reusable in net_firewalls when they eventually arrive too. net_firewalls can't be done at the moment because FwaaS is not widely deployed on OpenStack - by widely, we mean, not available on NeCTAR, JetStream or devstack out of the box)
- [x] Make floating ips standalone (also see #83)

(ping @baizhang @chiniforooshan @VJalili)

**Comment by VJalili** [comment]
> Join provider.block_store and provider.object_store into provider.storage. In addition, rename notion of object_store into buckets so provider.storage would have the following three modules: volumes, snapshots, and buckets

Generally I don't like changes to interfaces, but this one worth it, cos `block_store` and `object_store` has always puzzled me. However, I think we might be able to improve it a bit further. For instance, do think merging `volume`, `snapshot`, and `bucket` into one single entity makes any sense? 

In addition, `bucket` and `blob` are accepted terms, and maybe using the term `bucket` to refer to two objects `bucket` and `blob` would confusing. What about a more abstract term? e.g., just a random guess: `container`

**Comment by afgane** [comment]
What do you mean by merging `volume`, `snapshot`, and `bucket` into one single entity? The recommendation is to keep them grouped under `provider.storage` but each as an individual service, like so: `provider.storage.volumes.Volume`, `provider.storage.snapshots.Snapshot`, and `provider.storage.buckets.Bucket`.

Re. naming, we looked at AWS, Azure, GCE, and OpenStack as examples for common/accepted terminology. AWS and GCE use _bucket_ terminology; Azure uses _blobs & container_; OpenStack uses _container_ terminology. _Container_ seemed overloaded with container technologies (i.e., Docker) and with the plan to incorporate support for that tech in the future, we didn't want to pollute the namespace. At that point, _bucket_ prevailed so the thinking is to go with it.

**Comment by VJalili** [comment]
> What do you mean by merging volume, snapshot, and bucket into one single entity? The recommendation is to keep them grouped under provider.storage but each as an individual service, like so: provider.storage.volumes.Volume, provider.storage.snapshots.Snapshot, and provider.storage.buckets.Bucket.

I guess my question would be: could you store a given file on `volume`, `snapshot`, and `bucket`? You're putting all under `storage`, so I read: "I have three storage types, with some underlying differences, which I can use _all_ to store/retrieve data." 

- If this is a correct point (which I guess it is not), then you have overlapping functionality, and so you should have a common access to all. Compare it with read/write to SSD vs. HDD, although these are different technologies but you have unique read/write controllers at user level. So, if this point is correct, you need to provide a unified access to `bucket`, `volume`, and `snapshot`; such that user uses only one switch to change between the underlying technology without having to change how it read/write data.

- If this is an incorrect point (which I guess it is), then you're grouping conceptually different technologies. I am sure there is reasonable rational behind it, but it could be misleading, specially for a person who is not deeply familiar with these technologies --- (s)he would assume they are very similar, because they are grouped together, and (s)he could read/write a file/object to all.   


> Re. naming, we looked at AWS, Azure, GCE, and OpenStack as examples for common/accepted terminology. AWS and GCE use bucket terminology; Azure uses blobs & container; OpenStack uses container terminology. Container seemed overloaded with container technologies (i.e., Docker) and with the plan to incorporate support for that tech in the future, we didn't want to pollute the namespace. At that point, bucket prevailed so the thinking is to go with it.

That makes sense.

**Comment by afgane** [comment]
The storage module would group storage resources and not deal with files or how data is managed. So `volume`, `snapshot`, and `bucket` modules offer management capabilities for respective storage resources but how those are used is up to the developer. Technically, each of the three offers different functionality and features so they're not really redundant. One that's still missing would be a managed file system but not all providers support that so until then these are the three available storage technologies. 

The current structure (i.e., before here proposed change) differentiates between storage type at the library root level but it feels more consistent to have only a single `storage` as it fits better with the other modules, namely `compute`, `security`, and `networking`.

**Comment by VJalili** [comment]
So we agree on the second point I mentioned :) I think we could agree on `storage` name for the time being, and refactor in future in case it cause some misunderstanding.

**Comment by nuwang** [comment]
An additional two things is that we are planning to do is to make FloatingIPs and SecurityGroupRules be independent classes, moving their logic out into services. So security group rules would still be sg.rules, but you can do sg.rules.create(), sg.rules.get() and for sg in sg.rules etc, for greater consistency. Ditto for floating ips.

Task list for this:
- [ ] Rename `provider.compute.instance_types` → `provider.compute.vm_types` and consequently `InstanceType` resource to `VMType`
- [ ] Rename method `Instance.terminate`→ `Instance.delete`
- [ ] Rename `provider.security.security_groups` → `provider.security.vm_firewall`
- [ ] Plan for eventual implementation of `provider.security.net_firewall`, representing network ACLs
- [ ] Join `provider.block_store` and `provider.object_store` into `provider.storage`. In addition, rename notion of `object_store` into `buckets` so `provider.storage` would have the following three modules: `volumes`, `snapshots`, and `buckets`
- [ ] Make firewall rules standalone (The resultant firewall rules class may potentially be reusable in net_firewalls when they eventually arrive too. net_firewalls can't be done at the moment because FwaaS is not widely deployed on OpenStack - by widely, we mean, not available on NeCTAR, JetStream or devstack out of the box)
- [ ] Make floating ips standalone

@baizhang @chiniforooshan @mbookman @VJalili 
We've started on this work already but since this refactoring work may create a bit of a moving target, what we propose is that you only merge up to commit: https://github.com/gvlproject/cloudbridge/commit/5145707b6b505d4e152e099952506e2f9dcbf091
We can merge these refactoring commits in at leisure.

**Comment by nuwang** [comment]
The work has been completed in the following:
1. provider.compute.instance_types → provider.compute.vm_types in commit: https://github.com/gvlproject/cloudbridge/commit/3df1161aa751e66d65cffd34032e61d61070095e
2. Instance.terminate→ Instance.delete in commit: https://github.com/gvlproject/cloudbridge/commit/3df1161aa751e66d65cffd34032e61d61070095e
3. security_groups -> vm_firewall in PR: https://github.com/gvlproject/cloudbridge/pull/89
4. provider.security.net_firewall: Deferred till OpenStack support available
5. Join provider.block_store and provider.object_store into provider.storage in commit:
https://github.com/gvlproject/cloudbridge/commit/940fc7504d4bee75180816e70f6f67d7f608402c 
6. Make firewall rules standalone: https://github.com/gvlproject/cloudbridge/commit/175ee982db57b3833f892a04007d4829ec03a112
7. Make floating ips standalone: https://github.com/gvlproject/cloudbridge/commit/22f5a152fe02e0617aacf667fcb04104da6d99c3
8. In addition, the bucket object related methods have been moved to bucket.objects for uniformity's sake in commit. I don't know whether it's necessarily a great idea, but since we've moved everything else, that alone seems to be the only remaining inconsistent service, so I've gone ahead and moved that too. This will also affect you @VJalili : https://github.com/gvlproject/cloudbridge/commit/23fc4b0297566451b3fc4c28924c87c26bf3ff9d

   This means that it's necessary to slightly alter the bucket access code to use bucket.objects.create('test') instead of bucket.create_object()
and bucket.objects.get() instead of bucket.get() etc., making bucket_objects consistent with the rest.

   ```
    bucket.objects.list()
    bucket_obj = bucket.objects.get('id')
    for obj in bucket.objects:
         print(obj)
   ```
We can roll this back if it seems like a not so great idea.

**Comment by afgane** [comment]
Nice job overall!
Moving the bucket object handling methods feels like a good idea, I'm just not sure about the `BucketContainer` class name (https://github.com/gvlproject/cloudbridge/commit/23fc4b0297566451b3fc4c28924c87c26bf3ff9d#diff-94d4aadb8e485e76cac35132939f5383R2098). Perhaps `BucketObjects`? So we'd have a parallel with an individual `BucketObject`?

**Comment by nuwang** [comment]
That was chosen to match this (VMFirewallRuleContainer): https://github.com/gvlproject/cloudbridge/commit/175ee982db57b3833f892a04007d4829ec03a112#diff-d07c836fa7812460062a81d2c0095263R670

I avoided calling it "Service" since it's not in the service class. I guess we should choose something that would make sense in both scenarios. The only saving grace is that the name is not directly exposed to the user, so we can rename this at leisure to something sensible.

**Comment by nuwang** [comment]
Closing this issue since all items are completed except for "Plan for eventual implementation of provider.security.net_firewall, representing network ACLs". Will create a new tracking issue tagged as a future enhancement.
